(SIMP-2462) Update Versions
simp/pupmod-simp-simp_grafana pull request #14
Opened 2017-01-12 18:59 UTC by jeannegreulich

updated the requires and metadata.json files

SIMP-2462 #comment simp_granfana updated

2017-01-17 18:19 UTC, jeefberkey commented
Updating this module

2017-01-18 22:53 UTC, nick-markowski requested changes
I'm making a patch. It's gonna be a great patch; the best patch.

2017-01-19 02:18 UTC, nick-markowski requested changes

2017-01-19 02:18 UTC, nick-markowski commented on manifests/params.pp
> +  $base_dn = simplib::lookup('simp_options::ldap::base_dn', { 'default_value' => 'dc=invalid' } )
simplib::ldap::domain_to_dn?

2017-01-19 14:07 UTC, jeefberkey commented on manifests/params.pp
> +  $base_dn = simplib::lookup('simp_options::ldap::base_dn', { 'default_value' => 'dc=invalid' } )
What's that?

2017-01-19 15:19 UTC, nick-markowski commented on manifests/params.pp
> +  $base_dn = simplib::lookup('simp_options::ldap::base_dn', { 'default_value' => 'dc=invalid' } )
The new default for base_dn

2017-01-23 16:37 UTC, nick-markowski requested changes
I'll merge after a changelog update

2017-01-23 17:18 UTC, nick-markowski approved these changes

2017-01-23 17:21 UTC, merged