(SIMP-3164) Update static assets
simp/pupmod-simp-simp_grafana pull request #21
Opened 2017-05-30 21:01 UTC by op-ct

This commit normalizes static assets with other SIMP Puppet modules.
In particular, Travis CI is configured to include Puppet 4.10.

SIMP-3164 #comment Updated simp-simp_grafana

2017-05-31 20:46 UTC, lnemsick-simp requested changes

2017-05-31 20:46 UTC, lnemsick-simp commented on Gemfile
> +  gem 'simp-rake-helpers', ENV.fetch('SIMP_RAKE_HELPERS_VERSION', '~> 3.0')
Missing toml gem.

2017-05-31 20:46 UTC, lnemsick-simp commented on Gemfile
> +  gem 'simp-beaker-helpers', ENV.fetch('SIMP_BEAKER_HELPERS_VERSION', '~> 1.5')
why is this bumped down?

2017-05-31 20:46 UTC, lnemsick-simp commented on Gemfile
> +  gem 'simp-rake-helpers', ENV.fetch('SIMP_RAKE_HELPERS_VERSION', '~> 3.0')
why is SIMP_RAKE_HELPERS_VERSION bumped down?

2017-06-06 18:34 UTC, jeefberkey approved these changes

2017-06-06 19:06 UTC, lnemsick-simp approved these changes

2017-06-06 19:09 UTC, lnemsick-simp commented
Please don't merge until I run the acceptance tests.  Should not have accepted changes before I was done testing.

2017-06-06 21:43 UTC, lnemsick-simp approved these changes
Acceptance test fails, but appears to be independent of static assets update.

2017-06-06 21:44 UTC, merged